### ISSUE TITLE
2019-version tag needed

### ISSUE THREAD

**Issue by topherbuckley** [oist/skillpill-git#13]
@chrisb2244 can you either add me as a contributor or add a tag to the most recent commit so we don't lose track of what was used in 2019 before I move on to making the 2020 version?

Looks like I can't do this via a PR according to [this](https://stackoverflow.com/a/12279290) but happy to do it if you know another way around it. I made the tag in [my fork](https://github.com/topherbuckley/skillpill-git/releases) but don't see a way to push this to the oist repo without higher privileges.

**Comment by jiegillet** [comment]
I'll add you to the contributors.

Can tagging be done in GitHub directly? I don't recall but I'll look around.

Cheers!

**Comment by jiegillet** [comment]
We can do releases in GitHub but not tags. Tags are more appropriate.
You have write access to the repo now, feel free to tag it yourself if you want, otherwise @chrisb2244 or I can do it.

**Comment by topherbuckley** [comment]
I added the 2019 tag.
